### ISSUE TITLE
404 Page Needed

### ISSUE THREAD

**Issue by AIGamesDeveloper** [AspectOS/aspectos.github.io#15]
I think we need a 404 page. It doesn't look good for a GitHub Pages error to be there instead. Does anybody know how to make one?

**Comment by NILL2021** [comment]
I'll take this one

**Comment by AIGamesDeveloper** [comment]
> I'll take this one

Alright

**Comment by Kraken773** [comment]
I could style it, but I don't know how to make one. (This is ant, it's my long forgotten old account)

**Comment by AIGamesDeveloper** [comment]
> I could style it, but I don't know how to make one. (This is ant, it's my long forgotten old account)

Great! We need to style this error page

**Comment by TheMowgliMan** [comment]
Remember to use BootStrap to make it look like the rest of the site.

Im on mobile, dont be suprised if this message is OOF

**Comment by Mbrick2** [comment]
Added but waiting for toaster for the real one

**Comment by NILL2021** [comment]
> Added but waiting for toaster for the real one

I was asleep

**Comment by Mbrick2** [comment]
Resolved by #16. Thanks Toaster
