### ISSUE TITLE
Favicon won't show up by tab title

### ISSUE THREAD

**Issue by yoo832** [AspectOS/aspectos.github.io#31]
Ya know when you see the logo by the tab page title? It won't show up on anything except the homepage.
Can someone fix it?

Visual explanation:

![image](https://user-images.githubusercontent.com/88053295/164815268-1236a6dc-df96-4422-b63e-40571cca1eac.png)

![image](https://user-images.githubusercontent.com/88053295/164815283-4b40b221-c204-47f5-906e-d1322aca9be5.png)

![image](https://user-images.githubusercontent.com/88053295/164815297-2c006cea-dc37-402b-8f2f-503ad6ad3444.png)

**Comment by NILL2021** [comment]
Should be fixed now.

**Comment by DreamyCodes** [comment]
> Should be fixed now.

Whoa, seeing you just post that was weird.
