### ISSUE TITLE
Incorrect Redirect

### ISSUE THREAD

**Issue by qloakongithub** [AspectOS/aspectos.github.io#33]
On the 403 page, whenever you try to go to home using the navbar, it sends you to https://aspectos.github.io/aspectosteam.github.io. Test it yourself [here](https://aspectos.github.io/403)

**Comment by Mbrick2** [comment]
Resolved

**Comment by Mbrick2** [comment]
Didn't work. Seems to be with the fact thats its a "403"

**Comment by Mbrick2** [comment]
Found the true error. It linking to the old URL.

**Comment by Mbrick2** [comment]
Still doesn't fix

**Comment by qloakongithub** [comment]
Resolved.

**Comment by NILL2021** [comment]
The reason was because the dummy page used this link. I fixed the dummy page but forgot to fix 403

**Comment by Mbrick2** [comment]
[]()
