### ISSUE TITLE
Download links expired

### ISSUE THREAD

**Issue by WhatDoWeDoNowFromScratch** [AspectOS/aspectos.github.io#37]
Download links on /download.html still go to the site, but says "File has expired, and is no longer on this server"

**Comment by AIGamesDeveloper** [comment]
As of right now, I cannot download any macOS or Windows files since my school blocked Turbowarp Packager. But we will try to fix this ASAP

**Comment by qloakongithub** [comment]
Fixing.

**Comment by qloakongithub** [comment]
Resolved.
