### ISSUE TITLE
Random Button on Footer

### ISSUE THREAD

**Issue by AIGamesDeveloper** [AspectOS/aspectos.github.io#41]
https://user-images.githubusercontent.com/94424871/165116579-d9066530-e918-4711-ba7f-5e201d5354bf.mp4

As you can see, there is a random button on the footer and it doesn't go anywhere.

**Comment by yoo832** [comment]
On it.

Sincerely, yooit_32<https://scratch.mit.edu/users/yooit_32/>.
​
________________________________

**Comment by Skippy-the-derg** [comment]
Turn it into a light/dark mode button ✋

**Comment by AIGamesDeveloper** [comment]
> Turn it into a light/dark mode button ✋

This would be a good idea but I don't know if others would approve
And it might look weird to have a button that says "Dark Mode" on the bottom
