### ISSUE TITLE
The Ukraine card and the nav are touching, and it doesn't look the greatest

### ISSUE THREAD

**Issue by Skippy-the-derg** [AspectOS/aspectos.github.io#44]
![Screenshot 2022-04-25 3 33 23 PM](https://user-images.githubusercontent.com/98895095/165160986-c02039b5-90b4-4033-95a5-fb6a97e32d0b.png)

I can't fix (you :fnafmoment:) it.

**Comment by AIGamesDeveloper** [comment]
I was about to make this

**Comment by yoo832** [comment]
just add
`<br />`

**Comment by TheMowgliMan** [comment]
Use CSS margin.

**Comment by Mbrick2** [comment]
Fixed

**Comment by Mbrick2** [comment]
Mistake. Fixable by #46

**Comment by NILL2021** [comment]
Has this been fixed? I'm on an issue closing spree.

**Comment by Mbrick2** [comment]
> Has this been fixed? I'm on an issue closing spree.

It will be when #46 is merged

**Comment by NILL2021** [comment]
> > Has this been fixed? I'm on an issue closing spree.
> 
> It will be when #46 is merged

In that case, i guess i'll close it.
