### ISSUE TITLE
Ukraine Card Blue?

### ISSUE THREAD

**Issue by AIGamesDeveloper** [AspectOS/aspectos.github.io#45]
Hey, so I recently saw that the Ukraine Card was blue. Is this intentional for light mode users? If not, then can we fix this, please? Thanks!

**Comment by Mbrick2** [comment]
Its intentional (I think. I believe it was committed in the last 5 PRs)

**Comment by Mbrick2** [comment]
I'll revert this in #46

**Comment by Skippy-the-derg** [comment]
I think it looks good 👍
