### ISSUE TITLE
Deploying this on the GoDaddy domain

### ISSUE THREAD

**Issue by Mbrick2** [AspectOS/aspectos.github.io#47]
Instead of moving from Github to GoDaddy we can deploy the website to the GoDaddy domain with Github Pages. See [this](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site) for how to do it.

**Comment by AIGamesDeveloper** [comment]
I agree with this

**Comment by NILL2021** [comment]
I agree

**Comment by AIGamesDeveloper** [comment]
As of right now, KidC has not done anything with the domain. And I do not want to use that domain for the AspectOS website. Only the Aspect Inc. Website
