### ISSUE TITLE
Website URL not working?

### ISSUE THREAD

**Issue by Skippy-the-derg** [AspectOS/aspectos.github.io#51]
Didn't the person buy the domain? 
Explain:
![Screenshot_20220426-091423_Samsung Internet](https://user-images.githubusercontent.com/98895095/165308353-649e220a-cce4-42a7-8004-a16c3ae33241.png)
Also legit Samsung Internet browser is my favorite

**Comment by AIGamesDeveloper** [comment]
On mobile, it works for me. Can you check if it works for you at the moment?

**Comment by AIGamesDeveloper** [comment]
> On mobile, it works for me. Can you check if it works for you at the moment?

The only thing that isn't working is the home page. The other pages seem to work

**Comment by DreamyCodes** [comment]
> On mobile, it works for me. Can you check if it works for you at the moment?

Doesn’t work for me

**Comment by NILL2021** [comment]
it works for me on pc, but not mobile

**Comment by AIGamesDeveloper** [comment]
> it works for me on pc, but not mobile

It doesn't work for me on PC. This is really strange

**Comment by Skippy-the-derg** [comment]
> > On mobile, it works for me. Can you check if it works for you at the moment?
> 
> The only thing that isn't working is the home page. The other pages seem to work

Me too. My school actually blocked the homepage because it is "categorized as parked"

**Comment by AIGamesDeveloper** [comment]
> > > On mobile, it works for me. Can you check if it works for you at the moment?
> > 
> > 
> > The only thing that isn't working is the home page. The other pages seem to work
> 
> Me too. My school actually blocked the homepage because it is "categorized as parked"

My school blocked it because it couldn't establish a secure connection

**Comment by AIGamesDeveloper** [comment]
The website seems to be working for me now and on my phone. If you have any more problems, please make a new issue. Thanks!
