### ISSUE TITLE
@Kidcoder427's domain isn't working - Should we stay on Pages?

### ISSUE THREAD

**Issue by yoo832** [AspectOS/aspectos.github.io#54]
![image](https://user-images.githubusercontent.com/88053295/165345328-871bdf4d-4a9a-4994-a32f-354ad6895ac9.png)

Plus, GoDaddy says that it's parked.

**Comment by AIGamesDeveloper** [comment]
I think that going back to pages is the best thing to do. This is strange...

**Comment by TheMowgliMan** [comment]
> I think that going back to pages is the best thing to do. This is strange...

We never left pages. It's likely that it hasn't been configured yet properly. Someone made aspectos.github.io redirect to aspectllc.net, we can just remove that for now.

**Comment by TheMowgliMan** [comment]
It says that KidC still needs to point the domain to aspectos.github.io. He should follow the tut [https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site](here).

**Comment by yoo832** [comment]
why doesn't @Kidcoder427 directly link the URL to the site?

**Comment by AIGamesDeveloper** [comment]
> > I think that going back to pages is the best thing to do. This is strange...
> 
> We never left pages. It's likely that it hasn't been configured yet properly. Someone made aspectos.github.io redirect to aspectllc.net, we can just remove that for now.

Oh ok then
Changing title...

**Comment by NILL2021** [comment]
So it's probably because KidC still needs to link the four A records on godaddy to the GH pages IP addresses. Because it's basically resolved, i'm closing this. If KidC knows why this isn't working, and it is not any of the reasons listed on this issue, they should create a post on the discussion tab.
