### ISSUE TITLE
Dark Mode Problems

### ISSUE THREAD

**Issue by AIGamesDeveloper** [AspectOS/aspectos.github.io#59]
Dark Mode doesn't work for all pages except the home page.
First, let's see the problems with the home page

![Screenshot 2022-04-30 7 32 32 AM](https://user-images.githubusercontent.com/94424871/166110805-1bb08b93-ed62-43cd-8351-c34833fd580c.png)
![Screenshot 2022-04-30 7 32 19 AM](https://user-images.githubusercontent.com/94424871/166110808-16586d96-3302-4334-9970-209426f9229d.png)

Now let's see the other pages

![Screenshot 2022-04-30 7 40 56 AM](https://user-images.githubusercontent.com/94424871/166110816-0bdb6f80-0ceb-4e98-9f3a-47b36433ccf8.png)
![Screenshot 2022-04-30 7 32 43 AM](https://user-images.githubusercontent.com/94424871/166110817-6e751a3e-bf16-4421-a77e-e210eb059315.png)

https://user-images.githubusercontent.com/94424871/166110871-768b10c4-ce69-4b33-8bbb-9cc6c077412e.mp4

**Comment by Mbrick2** [comment]
Weird. I'll start fixing it now

**Comment by Mbrick2** [comment]
Should be fixed
