### ISSUE TITLE
Favicon source wont work

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [AspectOS/aspectos.github.io#6]
https://github.com/AspectOSTeam/aspectosteam.github.io/blob/ee9651c88e623fd379abce97c8d4066cb78a2fd6/index.html#L20
Since the Glitch favicon is blocked, I decided to change the source. Does anyone know why it won't work?

**Comment by ILOVETOMAKESTUFF** [comment]
Wait, I think I found a bug

**Comment by Mbrick2** [comment]
Think I fixed it. Waiting for deployment

**Comment by ILOVETOMAKESTUFF** [comment]
Now the hole site is empty

**Comment by Mbrick2** [comment]
> Now the whole site is empty

Weird. All I did is change a link

**Comment by ILOVETOMAKESTUFF** [comment]
> > Now the whole site is empty
> 
> Weird. All I did is change a link

For some reason, you put the CSS into comments. I undid it, it should hopefully work now

**Comment by Mbrick2** [comment]
Fixed
