### ISSUE TITLE
[Bug]: Issues with light mode

### ISSUE THREAD

**Issue by TheMowgliMan** [AspectOS/aspectos.github.io#61]
### Steps to reproduce the issue?

If your browser defaults to Dark Mode, use the "Toggle Theme" button in the footer.

### What happened?

In light mode, certain text (Like most of the text, and some stuff in the footer) stays white, making it unreadable. Obviously, I didn't expect this to happen.

**Comment by AIGamesDeveloper** [comment]
I will check it out and see if I can fix it. Thank you for pointing that out

**Comment by AIGamesDeveloper** [comment]
> I will check it out and see if I can fix it. Thank you for pointing that out

Alright, so I do see the problem with it. I will see what I can do

**Comment by Mbrick2** [comment]
Resolved by #63
