### ISSUE TITLE
The favicon is gone on the homepage

### ISSUE THREAD

**Issue by Skippy-the-derg** [AspectOS/aspectos.github.io#64]
**Describe the bug**
Favicon isn't on the homepage, but it's there on other pages.

**Screenshots**
![Screenshot 2022-05-02 12 39 54 PM](https://user-images.githubusercontent.com/98895095/166288710-4dc4487b-aded-4bf1-b1c9-52f87d69e931.png)

**Desktop (please complete the following information):**

- OS: Chromium? Idk.
- Browser: Chrome
- Version: ... don't actually know. I'm guessing 98.0.4758.107.

**Comment by AIGamesDeveloper** [comment]
I saw this too. I will fix it right now

**Comment by AIGamesDeveloper** [comment]
> I saw this too. I will fix it right now

It has been fixed. If you have any problems, please let us know
