### ISSUE TITLE
Custom Themes for Website

### ISSUE THREAD

**Issue by PoIygon** [AspectOS/aspectos.github.io#65]
We could make custom themes like a scratch theme or a ocular theme for AspectOS. 

First we would need to move all of the css variables to a thing called :root {}

Then we need to make a javascript file that changes the class of the body to the next theme every time you click the toggle theme button (which you already have)

I think I could make this into a PR if I am not lazy

**Comment by AIGamesDeveloper** [comment]
This would be a good idea!
I like the idea of different modes in the AspectOS website

**Comment by PoIygon** [comment]
> This would be a good idea!
> I like the idea of different modes in the AspectOS website

Yeah it would be great! Could we use sass to make it easier to write the css?

**Comment by yoo832** [comment]
> > This would be a good idea!
> > I like the idea of different modes in the AspectOS website
> 
> Yeah it would be great! Could we use sass to make it easier to write the css?

I guess.
