### ISSUE TITLE
Use Fetch to update staff list

### ISSUE THREAD

**Issue by PoIygon** [AspectOS/aspectos.github.io#66]
every time you connect to the page it will do a fetch to the staff list api on scratch and display the information

**Comment by AIGamesDeveloper** [comment]
how easy is it?

**Comment by PoIygon** [comment]
You fetch to the staff list in the scratch api and then do some javascript that repeats the same div with the same content until it reaches the end or something

**Comment by AIGamesDeveloper** [comment]
Sorry, I don't think we will be working on this anytime soon
